const DB_NAME='linguaflow-db', STORE='state', KEY='app-state';
const DAY_NAMES=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const DAY_FULL=['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'];
const fmtDate=d=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d);
const isoDate=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mondayOf=d=>{const x=new Date(d),day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);x.setHours(0,0,0,0);return x};
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};

const demo=()=>{
  const mon=mondayOf(new Date());
  const students=[
    ['Анна','Петрова','individual','Елена Орлова',[0,3],'16:00','@anna_mom','Уровень A2',3,8],
    ['Максим','Волков','pair','Елена Орлова',[1,4],'17:00','+380 67 111 22 33','Подготовка к IELTS',7,8],
    ['София','Коваленко','group','Мария Соколова',[0,2],'18:00','@sofia_k','Teen B1',1,8],
    ['Артём','Бондарь','group','Мария Соколова',[0,2],'18:00','+380 93 555 77 11','Teen B1',6,8],
    ['Ева','Мельник','pair','Елена Орлова',[1,4],'17:00','@eva_m','Пара с Максимом',2,8],
    ['Даниил','Шевченко','individual','Анна Литвин',[2,5],'12:00','@daniil','Business English',10,12]
  ].map((s,i)=>({id:`s${i+1}`,first:s[0],last:s[1],format:s[2],teacher:s[3],days:s[4],time:s[5],scheduleSlots:s[4].map(day=>({day,time:s[5]})),contact:s[6],note:s[7],remaining:s[8],total:s[9],history:[]}));
  const groups=[{id:'g1',name:'Teen B1',type:'group',teacher:'Мария Соколова',studentIds:['s3','s4'],color:'#f09b42'},{id:'g2',name:'Максим + Ева',type:'pair',teacher:'Елена Орлова',studentIds:['s2','s5'],color:'#26a875'}];
  const lessons=[
    ['l1',0,'10:00','11:00','individual','s1',null,'Елена Орлова','done'],['l2',0,'13:00','14:00','group',null,'g1','Мария Соколова','planned'],
    ['l3',1,'11:00','12:00','individual','s6',null,'Анна Литвин','planned'],['l4',1,'17:00','18:00','pair',null,'g2','Елена Орлова','planned'],
    ['l5',2,'12:00','13:00','individual','s6',null,'Анна Литвин','planned'],['l6',2,'18:00','19:00','group',null,'g1','Мария Соколова','planned'],
    ['l7',3,'16:00','17:00','individual','s1',null,'Елена Орлова','planned'],['l8',4,'17:00','18:00','pair',null,'g2','Елена Орлова','planned']
  ].map(x=>({id:x[0],date:isoDate(addDays(mon,x[1])),start:x[2],end:x[3],type:x[4],studentId:x[5],groupId:x[6],teacher:x[7],status:x[8],note:'',attendance:x[5]?{[x[5]]:{status:'present',note:''}}:{},chargedStudentIds:x[8]==='done'&&x[5]?[x[5]]:[]}));
  return {students,groups,lessons,teachers:['Елена Орлова','Мария Соколова','Анна Литвин'],assistantMessages:[{role:'assistant',text:'Здравствуйте! Я могу управлять расписанием, посещаемостью и преподавателями. Напишите команду обычными словами.'}],settings:{school:'LinguaFlow English School'},version:2};
};

let state=demo();let currentView='dashboard';let calendarMode='week';let focusDate=new Date();let filters={teacher:'',status:'',query:''};
const root=document.querySelector('#viewRoot');

function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function load(){try{const db=await openDB();const saved=await new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(saved)state=saved}catch(e){console.warn('IndexedDB недоступна',e)}normalizeState();render()}
async function save(){try{const db=await openDB();await new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(state,KEY);r.onsuccess=res;r.onerror=()=>rej(r.error)})}catch(e){localStorage.setItem(KEY,JSON.stringify(state))}}
function normalizeState(){state.teachers=state.teachers||[];state.assistantMessages=state.assistantMessages||[{role:'assistant',text:'Здравствуйте! Я могу управлять расписанием, посещаемостью и преподавателями. Напишите команду обычными словами.'}];state.assistantUndoStack=Array.isArray(state.assistantUndoStack)?state.assistantUndoStack:[];state.students.forEach(s=>{if(!Array.isArray(s.scheduleSlots))s.scheduleSlots=(s.days||[]).map(day=>({day,time:s.time||'16:00'}));s.scheduleSlots=s.scheduleSlots.map(x=>({day:Number(x.day),time:x.time||'16:00'})).sort((a,b)=>a.day-b.day);s.days=s.scheduleSlots.map(x=>x.day);s.time=s.scheduleSlots[0]?.time||s.time||'16:00'});state.lessons.forEach(l=>{const ids=affectedStudents(l);l.attendance=l.attendance||Object.fromEntries(ids.map(id=>[id,{status:'present',note:''}]));if(!Array.isArray(l.chargedStudentIds))l.chargedStudentIds=l.status==='done'?[...ids]:[]})}
function assistantCoreSnapshot(){return JSON.stringify({students:state.students,groups:state.groups,lessons:state.lessons,teachers:state.teachers,settings:state.settings})}
function restoreAssistantSnapshot(snapshot){const data=JSON.parse(snapshot);state.students=data.students||[];state.groups=data.groups||[];state.lessons=data.lessons||[];state.teachers=data.teachers||[];state.settings=data.settings||state.settings;state.pendingAssistantAction=null;state.lastAssistantAction=null;normalizeState()}
function isAssistantUndoCommand(text){const low=text.toLowerCase().replace(/ё/g,'е');return /(отмени|отменить)\s+(все|последн)/.test(low)}
async function runAssistantCommand(text){const before=assistantCoreSnapshot(),isUndo=isAssistantUndoCommand(text),answer=await executeAssistantCommand(text),after=assistantCoreSnapshot();if(!isUndo&&before!==after){state.assistantUndoStack.push(before);state.assistantUndoStack=state.assistantUndoStack.slice(-50)}return answer}
function studentName(id){const s=state.students.find(x=>x.id===id);return s?`${s.first} ${s.last}`:'Ученик'}
function groupName(id){return state.groups.find(x=>x.id===id)?.name||'Группа'}
function lessonName(l){return l.groupId?groupName(l.groupId):studentName(l.studentId)}
function formatName(f){return({individual:'Индивидуально',pair:'Пара',group:'Группа'})[f]||f}
function studentScheduleText(s){const slots=s.scheduleSlots?.length?s.scheduleSlots:(s.days||[]).map(day=>({day,time:s.time||'16:00'}));return slots.length?slots.map(x=>`${DAY_NAMES[x.day]} ${x.time}`).join(' · '):'Не задано'}
function toast(msg){const e=document.querySelector('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
function setHeader(title,sub){document.querySelector('#pageTitle').textContent=title;document.querySelector('#pageSubtitle').textContent=sub}
function render(){document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===currentView));({dashboard:renderDashboard,calendar:renderCalendar,students:renderStudents,groups:renderGroups,subscriptions:renderSubscriptions,assistant:renderAssistant,settings:renderSettings}[currentView]||renderDashboard)()}
function optionList(items,value=''){return items.map(x=>`<option value="${esc(typeof x==='string'?x:x.id)}" ${value===(typeof x==='string'?x:x.id)?'selected':''}>${esc(typeof x==='string'?x:x.name)}</option>`).join('')}

function renderDashboard(){setHeader('Добрый день!','Вот что происходит в школе сегодня');const today=isoDate(new Date());const todays=state.lessons.filter(l=>l.date===today).sort((a,b)=>a.start.localeCompare(b.start));const active=state.students.length;const low=state.students.filter(s=>s.remaining<=2);
 root.innerHTML=`<div class="stats"><div class="stat-card"><span class="stat-icon purple">♙</span><div><small>Всего учеников</small><strong>${active}</strong></div></div><div class="stat-card"><span class="stat-icon green">▦</span><div><small>Занятий сегодня</small><strong>${todays.length}</strong></div></div><div class="stat-card"><span class="stat-icon orange">◫</span><div><small>Заканчивается абонемент</small><strong>${low.length}</strong></div></div><div class="stat-card"><span class="stat-icon red">♧</span><div><small>Групп и пар</small><strong>${state.groups.length}</strong></div></div></div>
 <div class="dashboard-grid"><div class="card"><div class="card-head"><h2>Расписание на сегодня</h2><button class="secondary push" data-go="calendar">Открыть календарь</button></div><div class="card-body agenda">${todays.length?todays.map(agendaRow).join(''):`<div class="empty"><div class="empty-icon">☕</div>На сегодня занятий нет</div>`}</div></div>
 <div class="card"><div class="card-head"><h2>Нужно внимание</h2><span class="badge push">${low.length}</span></div><div class="card-body low-list">${low.length?low.map(s=>`<div class="low-row"><span class="avatar">${esc(s.first[0]+s.last[0])}</span><div class="student-cell"><strong>${esc(s.first+' '+s.last)}</strong><small>Осталось ${s.remaining} из ${s.total}</small><div class="progress"><i style="width:${s.remaining/s.total*100}%"></i></div></div><button class="icon-btn" data-edit-sub="${s.id}">›</button></div>`).join(''):`<div class="empty">Все абонементы в порядке</div>`}</div></div></div>`;
 bindCommon()}
function agendaRow(l){return `<div class="agenda-item"><div class="agenda-time">${esc(l.start)}</div><i class="agenda-bar" style="background:${l.type==='group'?'#f09b42':l.type==='pair'?'#26a875':'#6255e7'}"></i><div class="agenda-info"><strong>${esc(lessonName(l))}</strong><small>${formatName(l.type)} · ${esc(l.teacher)}</small></div><button class="badge ${l.status}" data-edit-lesson="${l.id}">${l.status==='done'?'Проведено':l.status==='cancelled'?'Отменено':'Запланировано'}</button></div>`}

function filteredLessons(){return state.lessons.filter(l=>(!filters.teacher||l.teacher===filters.teacher)&&(!filters.status||l.status===filters.status)&&(!filters.query||lessonName(l).toLowerCase().includes(filters.query.toLowerCase())))}
function renderCalendar(){setHeader('Расписание','Создавайте и переносите занятия');const period=calendarMode==='week'?`${fmtDate(mondayOf(focusDate))} — ${fmtDate(addDays(mondayOf(focusDate),6))}`:new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(focusDate);
 root.innerHTML=`<div class="toolbar"><button class="icon-btn" data-cal-prev>‹</button><button class="secondary" data-cal-today>Сегодня</button><button class="icon-btn" data-cal-next>›</button><strong>${period}</strong><span class="spacer"></span><select class="filter" id="teacherFilter"><option value="">Все преподаватели</option>${optionList(state.teachers,filters.teacher)}</select><select class="filter" id="statusFilter"><option value="">Все статусы</option><option value="planned" ${filters.status==='planned'?'selected':''}>Запланировано</option><option value="done" ${filters.status==='done'?'selected':''}>Проведено</option><option value="cancelled" ${filters.status==='cancelled'?'selected':''}>Отменено</option></select><div class="segmented"><button data-mode="week" class="${calendarMode==='week'?'active':''}">Неделя</button><button data-mode="month" class="${calendarMode==='month'?'active':''}">Месяц</button></div></div><div class="calendar-wrap">${calendarMode==='week'?weekHTML():monthHTML()}</div>`;bindCalendar()}
function weekHTML(){const mon=mondayOf(focusDate),hours=Array.from({length:12},(_,i)=>8+i),lessons=filteredLessons();let h='<div class="week-grid"><div class="week-head"></div>'+DAY_NAMES.map((d,i)=>{const date=addDays(mon,i);return `<div class="week-head ${isoDate(date)===isoDate(new Date())?'today':''}">${d}<strong>${date.getDate()}</strong></div>`}).join('');
 hours.forEach(hour=>{h+=`<div class="time-cell">${String(hour).padStart(2,'0')}:00</div>`;for(let d=0;d<7;d++){const date=isoDate(addDays(mon,d));const inCell=lessons.filter(l=>l.date===date&&parseInt(l.start)===hour);h+=`<div class="day-cell" data-date="${date}" data-time="${String(hour).padStart(2,'0')}:00">${inCell.map(l=>`<div draggable="true" class="lesson ${l.type}" data-lesson="${l.id}"><strong>${esc(l.start)} ${esc(lessonName(l))}</strong><small>${esc(l.teacher.split(' ')[0])}</small></div>`).join('')}</div>`} });return h+'</div>'}
function monthHTML(){const first=new Date(focusDate.getFullYear(),focusDate.getMonth(),1),start=mondayOf(first),lessons=filteredLessons();let h='<div class="month-grid">'+DAY_NAMES.map(d=>`<div class="month-label">${d}</div>`).join('');for(let i=0;i<42;i++){const date=addDays(start,i),key=isoDate(date),muted=date.getMonth()!==focusDate.getMonth(),ls=lessons.filter(l=>l.date===key).sort((a,b)=>a.start.localeCompare(b.start));h+=`<div class="month-day ${muted?'muted':''}" data-date="${key}"><div class="month-date">${date.getDate()}</div>${ls.slice(0,4).map(l=>`<div class="month-event" data-edit-lesson="${l.id}">${l.start} · ${esc(lessonName(l))}</div>`).join('')}${ls.length>4?`<small>+ ещё ${ls.length-4}</small>`:''}</div>`}return h+'</div>'}
function bindCalendar(){document.querySelector('[data-cal-prev]').onclick=()=>{focusDate=addDays(focusDate,calendarMode==='week'?-7:-30);render()};document.querySelector('[data-cal-next]').onclick=()=>{focusDate=addDays(focusDate,calendarMode==='week'?7:30);render()};document.querySelector('[data-cal-today]').onclick=()=>{focusDate=new Date();render()};document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{calendarMode=b.dataset.mode;render()});document.querySelector('#teacherFilter').onchange=e=>{filters.teacher=e.target.value;render()};document.querySelector('#statusFilter').onchange=e=>{filters.status=e.target.value;render()};document.querySelectorAll('[data-edit-lesson]').forEach(b=>b.onclick=e=>openLesson(e.currentTarget.dataset.editLesson));document.querySelectorAll('.lesson').forEach(el=>{el.onclick=()=>openLesson(el.dataset.lesson);el.ondragstart=e=>e.dataTransfer.setData('text/plain',el.dataset.lesson)});document.querySelectorAll('.day-cell,.month-day').forEach(c=>{c.ondragover=e=>e.preventDefault();c.ondrop=async e=>{e.preventDefault();const l=state.lessons.find(x=>x.id===e.dataTransfer.getData('text/plain'));if(!l)return;l.date=c.dataset.date;if(c.dataset.time){const duration=parseInt(l.end)-parseInt(l.start)||1;l.start=c.dataset.time;l.end=`${String(parseInt(c.dataset.time)+duration).padStart(2,'0')}:00`}await save();render();toast('Занятие перенесено')};c.ondblclick=()=>openLesson(null,{date:c.dataset.date,start:c.dataset.time})})}

function renderStudents(){setHeader('Ученики',`${state.students.length} записей в базе`);const q=filters.query.toLowerCase(),items=state.students.filter(s=>(!filters.teacher||s.teacher===filters.teacher)&&(s.first+' '+s.last+' '+s.teacher+' '+s.contact).toLowerCase().includes(q));root.innerHTML=`<div class="toolbar"><label class="search"><span>⌕</span><input id="studentSearch" value="${esc(filters.query)}" placeholder="Поиск по имени или контакту"></label><select class="filter" id="studentTeacher"><option value="">Все преподаватели</option>${optionList(state.teachers,filters.teacher)}</select><span class="spacer"></span><button class="primary" data-add-student>＋ Добавить ученика</button></div><div class="table-card"><table><thead><tr><th>Ученик</th><th>Формат</th><th>Преподаватель</th><th>Дни и время</th><th>Абонемент</th><th>Контакт</th><th></th></tr></thead><tbody>${items.map(s=>`<tr><td><div class="student-cell"><strong>${esc(s.first+' '+s.last)}</strong><small>${esc(s.note||'Без заметки')}</small></div></td><td><span class="badge">${formatName(s.format)}</span></td><td>${esc(s.teacher)}</td><td>${esc(studentScheduleText(s))}</td><td><strong>${s.remaining}</strong> из ${s.total}</td><td>${esc(s.contact||'—')}</td><td><div class="row-actions"><button data-edit-student="${s.id}" title="Редактировать">✎</button><button data-delete-student="${s.id}" title="Удалить">×</button></div></td></tr>`).join('')}</tbody></table>${items.length?'':`<div class="empty">Ничего не найдено</div>`}</div>`;document.querySelector('[data-add-student]').onclick=()=>openStudent();document.querySelector('#studentSearch').oninput=e=>{filters.query=e.target.value;renderStudents()};document.querySelector('#studentTeacher').onchange=e=>{filters.teacher=e.target.value;renderStudents()};document.querySelectorAll('[data-edit-student]').forEach(b=>b.onclick=()=>openStudent(b.dataset.editStudent));document.querySelectorAll('[data-delete-student]').forEach(b=>b.onclick=()=>deleteStudent(b.dataset.deleteStudent))}

function renderGroups(){setHeader('Группы и пары','Несколько учеников — одно занятие');root.innerHTML=`<div class="toolbar"><span class="badge">Групп: ${state.groups.filter(g=>g.type==='group').length}</span><span class="badge">Пар: ${state.groups.filter(g=>g.type==='pair').length}</span><span class="spacer"></span><button class="primary" data-add-group>＋ Создать группу</button></div><div class="table-card"><table><thead><tr><th>Название</th><th>Тип</th><th>Преподаватель</th><th>Участники</th><th></th></tr></thead><tbody>${state.groups.map(g=>`<tr><td><strong>${esc(g.name)}</strong></td><td><span class="badge">${formatName(g.type)}</span></td><td>${esc(g.teacher)}</td><td>${g.studentIds.map(studentName).map(esc).join(', ')||'Нет участников'}</td><td><div class="row-actions"><button data-edit-group="${g.id}">✎</button><button data-delete-group="${g.id}">×</button></div></td></tr>`).join('')}</tbody></table></div>`;document.querySelector('[data-add-group]').onclick=()=>openGroup();document.querySelectorAll('[data-edit-group]').forEach(b=>b.onclick=()=>openGroup(b.dataset.editGroup));document.querySelectorAll('[data-delete-group]').forEach(b=>b.onclick=()=>deleteGroup(b.dataset.deleteGroup))}

function renderSubscriptions(){setHeader('Абонементы','Остатки и история списаний');const ordered=[...state.students].sort((a,b)=>a.remaining-b.remaining);root.innerHTML=`<div class="stats"><div class="stat-card"><span class="stat-icon purple">◫</span><div><small>Активных</small><strong>${ordered.length}</strong></div></div><div class="stat-card"><span class="stat-icon orange">!</span><div><small>Осталось 1–2 урока</small><strong>${ordered.filter(s=>s.remaining<=2).length}</strong></div></div><div class="stat-card"><span class="stat-icon green">✓</span><div><small>Проведено уроков</small><strong>${state.lessons.filter(l=>l.status==='done').length}</strong></div></div><div class="stat-card"><span class="stat-icon red">0</span><div><small>Закончились</small><strong>${ordered.filter(s=>s.remaining===0).length}</strong></div></div></div><div class="table-card"><table><thead><tr><th>Ученик</th><th>Пакет</th><th>Следующий урок</th><th>Осталось</th><th>Последнее изменение</th><th></th></tr></thead><tbody>${ordered.map(s=>{const used=Math.max(0,s.total-s.remaining),next=Math.min(used+1,s.total);return `<tr><td><strong>${esc(s.first+' '+s.last)}</strong></td><td>${s.total} уроков</td><td><span class="badge planned">${s.remaining>0?`${next}-й из ${s.total}`:'Абонемент завершён'}</span></td><td><strong style="color:${s.remaining<=2?'#e65e66':'#26a875'}">${s.remaining}</strong><div class="progress" style="width:100px"><i style="width:${s.remaining/s.total*100}%"></i></div></td><td>${s.history.at(-1)?`${fmtDate(new Date(s.history.at(-1).date))} · ${esc(s.history.at(-1).reason)}`:'Нет изменений'}</td><td><button class="secondary" data-edit-sub="${s.id}">Изменить</button></td></tr>`}).join('')}</tbody></table></div>`;document.querySelectorAll('[data-edit-sub]').forEach(b=>b.onclick=()=>openSubscription(b.dataset.editSub))}

function renderSettings(){setHeader('Настройки','Преподаватели, интеграции и данные');root.innerHTML=`<div class="settings-grid"><div class="card setting-card"><span class="eyebrow">КОМАНДА</span><h3>Преподаватели</h3><p>Добавляйте преподавателей и назначайте их ученикам, группам и занятиям.</p><div class="teacher-list">${state.teachers.map(t=>`<div class="teacher-row"><span class="avatar">${esc(t.split(' ').map(x=>x[0]).join('').slice(0,2))}</span><strong>${esc(t)}</strong><span class="spacer"></span><button class="icon-btn" data-edit-teacher="${esc(t)}" title="Переименовать">✎</button><button class="icon-btn" data-delete-teacher="${esc(t)}" title="Удалить">×</button></div>`).join('')}</div><button class="primary" id="addTeacher">＋ Добавить преподавателя</button></div><div class="card setting-card"><span class="eyebrow">КАЛЕНДАРЬ</span><h3>Импорт и экспорт ICS</h3><p>Экспортируйте расписание в Apple Calendar, Google Calendar или Outlook.</p><button class="secondary" id="icsExport">Экспортировать .ics</button></div><div class="card setting-card"><span class="eyebrow">ОБЛАЧНАЯ БАЗА</span><h3>Supabase</h3><p>Демо работает локально через IndexedDB. Для команды подключите Supabase по инструкции в README.</p><span class="badge planned">Готово к подключению</span></div><div class="card setting-card"><span class="eyebrow">РЕЗЕРВНАЯ КОПИЯ</span><h3>Экспорт данных</h3><p>Сохраните учеников, группы, занятия и историю абонементов в одном JSON-файле.</p><button class="secondary" id="jsonExport">Скачать копию</button></div><div class="card setting-card"><span class="eyebrow">ICLOUD</span><h3>Apple Calendar</h3><p>Приватный iCloud нельзя безопасно встроить без авторизации. Используйте ICS или будущий защищённый CalDAV-сервер.</p><span class="badge">Архитектура предусмотрена</span></div></div>`;document.querySelector('#icsExport').onclick=exportICS;document.querySelector('#jsonExport').onclick=exportJSON;document.querySelector('#addTeacher').onclick=()=>openTeacher();document.querySelectorAll('[data-edit-teacher]').forEach(b=>b.onclick=()=>openTeacher(b.dataset.editTeacher));document.querySelectorAll('[data-delete-teacher]').forEach(b=>b.onclick=()=>deleteTeacher(b.dataset.deleteTeacher))}

function openTeacher(oldName=''){modal(oldName?'Переименовать преподавателя':'Новый преподаватель','КОМАНДА',`<div class="field full"><label>Имя и фамилия</label><input name="name" required value="${esc(oldName)}" placeholder="Например: Ольга Иванова"></div><div class="form-actions"><button type="button" class="secondary" data-close>Отмена</button><button class="primary">Сохранить</button></div>`);const f=document.querySelector('#modalForm');f.onsubmit=async e=>{e.preventDefault();const name=new FormData(f).get('name').trim();if(!name)return;if(state.teachers.some(t=>t===name&&t!==oldName)){toast('Такой преподаватель уже есть');return}if(oldName){state.teachers[state.teachers.indexOf(oldName)]=name;state.students.forEach(s=>{if(s.teacher===oldName)s.teacher=name});state.groups.forEach(g=>{if(g.teacher===oldName)g.teacher=name});state.lessons.forEach(l=>{if(l.teacher===oldName)l.teacher=name})}else state.teachers.push(name);await save();closeModal();renderSettings();toast(oldName?'Имя преподавателя изменено':'Преподаватель добавлен')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal)}
async function deleteTeacher(name){const used=state.students.some(s=>s.teacher===name)||state.groups.some(g=>g.teacher===name)||state.lessons.some(l=>l.teacher===name&&l.status==='planned');if(used){toast('Сначала переназначьте активных учеников и будущие занятия');return}if(!confirm(`Удалить преподавателя «${name}»? История проведённых уроков сохранится.`))return;state.teachers=state.teachers.filter(t=>t!==name);await save();renderSettings();toast('Преподаватель удалён')}

function modal(title,eyebrow,html){document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalEyebrow').textContent=eyebrow;document.querySelector('#modalForm').innerHTML=html;document.querySelector('#modalBackdrop').hidden=false}
function closeModal(){document.querySelector('#modalBackdrop').hidden=true}
function openLesson(id,preset={}){
  const initialStart=preset.start||'16:00',initialEnd=`${String(Math.min(parseInt(initialStart)+1,23)).padStart(2,'0')}:00`;
  const l=state.lessons.find(x=>x.id===id)||{id:uid(),date:preset.date||isoDate(new Date()),start:initialStart,end:initialEnd,type:'individual',studentId:'',groupId:'',teacher:state.teachers[0]||'',status:'planned',note:'',attendance:{},chargedStudentIds:[]};
  modal(id?'Редактировать занятие':'Новое занятие','РАСПИСАНИЕ',`${id?`<input type="hidden" name="id" value="${id}">`:''}<div class="field"><label>Дата</label><input name="date" type="date" required value="${l.date}"></div><div class="field"><label>Формат</label><select name="type"><option value="individual" ${l.type==='individual'?'selected':''}>Индивидуально</option><option value="pair" ${l.type==='pair'?'selected':''}>Пара</option><option value="group" ${l.type==='group'?'selected':''}>Группа</option></select></div><div class="field"><label>Начало</label><input name="start" type="time" required value="${l.start}"></div><div class="field"><label>Окончание</label><input name="end" type="time" required value="${l.end}"></div><div class="field" id="studentField"><label>Ученик</label><select name="studentId"><option value="">Выберите ученика</option>${state.students.map(s=>`<option value="${s.id}" ${l.studentId===s.id?'selected':''}>${esc(s.first+' '+s.last)}</option>`).join('')}</select></div><div class="field" id="groupField"><label>Группа или пара</label><select name="groupId"><option value="">Выберите</option>${optionList(state.groups,l.groupId)}</select></div><div class="field"><label>Преподаватель</label><select name="teacher">${optionList(state.teachers,l.teacher)}</select></div><div class="field"><label>Статус урока</label><select name="status"><option value="planned" ${l.status==='planned'?'selected':''}>Запланирован</option><option value="done" ${l.status==='done'?'selected':''}>Проведён</option><option value="cancelled" ${l.status==='cancelled'?'selected':''}>Отменён — не списывать</option></select></div><div class="field full attendance-field"><label>Посещаемость и списание</label><div id="attendanceRows"></div><small>Урок списывается только у присутствующего ученика после статуса «Проведён».</small></div><div class="field full"><label>Причина отмены / заметка</label><textarea name="note" rows="2" placeholder="Например: ученик заболел">${esc(l.note)}</textarea></div><div class="form-actions">${id?'<button type="button" class="danger" id="deleteLesson">Удалить</button>':''}<button type="button" class="secondary" data-close>Отмена</button><button class="primary">Сохранить</button></div>`);
  const f=document.querySelector('#modalForm');
  const selectedIds=()=>f.type.value==='individual'?(f.studentId.value?[f.studentId.value]:[]):(state.groups.find(g=>g.id===f.groupId.value)?.studentIds||[]);
  const renderAttendance=()=>{const ids=selectedIds();document.querySelector('#attendanceRows').innerHTML=ids.length?ids.map(sid=>{const a=l.attendance?.[sid]||{status:'present',note:''};const s=state.students.find(x=>x.id===sid);const used=Math.max(0,(s?.total||0)-(s?.remaining||0));return `<div class="attendance-row"><strong>${esc(studentName(sid))}</strong><span class="lesson-number">Следующий: ${Math.min(used+1,s?.total||1)} из ${s?.total||1}</span><select name="attendance_${sid}" class="filter"><option value="present" ${a.status!=='absent'?'selected':''}>Присутствовал — списать</option><option value="absent" ${a.status==='absent'?'selected':''}>Не присутствовал — не списывать</option></select><input name="absenceNote_${sid}" value="${esc(a.note||'')}" placeholder="Причина отсутствия"></div>`}).join(''):'<div class="empty compact">Сначала выберите ученика или группу</div>'};
  const toggle=()=>{const individual=f.type.value==='individual';document.querySelector('#studentField').style.display=individual?'grid':'none';document.querySelector('#groupField').style.display=individual?'none':'grid';renderAttendance()};
  f.type.onchange=toggle;f.studentId.onchange=renderAttendance;f.groupId.onchange=renderAttendance;toggle();
  f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),v=Object.fromEntries(fd),studentId=v.type==='individual'?v.studentId:'',groupId=v.type==='individual'?'':v.groupId;const next={...l,...v,studentId,groupId,attendance:{},chargedStudentIds:[...(l.chargedStudentIds||[])]};const ids=affectedStudents(next);if(!ids.length){toast('Выберите ученика или группу');return}ids.forEach(sid=>next.attendance[sid]={status:fd.get(`attendance_${sid}`)||'present',note:fd.get(`absenceNote_${sid}`)||''});reconcileLessonCharges(next);const old=state.lessons.find(x=>x.id===id);id?Object.assign(old,next):state.lessons.push(next);await save();closeModal();render();toast(next.status==='cancelled'?'Урок отменён, абонемент не списан':'Занятие и посещаемость сохранены')};
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal);if(id)document.querySelector('#deleteLesson').onclick=()=>deleteLesson(id)
}
function affectedStudents(l){return l.studentId?[l.studentId]:(state.groups.find(g=>g.id===l.groupId)?.studentIds||[])}
function reconcileLessonCharges(l){const before=new Set(l.chargedStudentIds||[]),desired=new Set(l.status==='done'?affectedStudents(l).filter(id=>l.attendance?.[id]?.status!=='absent'):[]);for(const id of desired){if(before.has(id))continue;const s=state.students.find(x=>x.id===id);if(s&&s.remaining>0){s.remaining--;s.history.push({id:uid(),lessonId:l.id,date:new Date().toISOString(),delta:-1,reason:`Проведённый урок ${l.date}`})}}for(const id of before){if(desired.has(id))continue;const s=state.students.find(x=>x.id===id);if(s){s.remaining++;s.history.push({id:uid(),lessonId:l.id,date:new Date().toISOString(),delta:1,reason:`Урок ${l.date} отменён / ученик отсутствовал`})}}l.chargedStudentIds=[...desired]}
async function deleteLesson(id){if(!confirm('Удалить занятие?'))return;const l=state.lessons.find(x=>x.id===id);l.status='cancelled';reconcileLessonCharges(l);state.lessons=state.lessons.filter(x=>x.id!==id);await save();closeModal();render();toast('Занятие удалено, списания возвращены')}

function openStudent(id){
  const s=state.students.find(x=>x.id===id)||{id:uid(),first:'',last:'',format:'individual',teacher:state.teachers[0]||'',days:[],time:'16:00',scheduleSlots:[],contact:'',note:'',remaining:8,total:8,history:[]};
  const slots=s.scheduleSlots?.length?s.scheduleSlots:(s.days||[]).map(day=>({day,time:s.time||'16:00'}));
  modal(id?'Редактировать ученика':'Новый ученик','БАЗА УЧЕНИКОВ',`<div class="field"><label>Имя</label><input name="first" required value="${esc(s.first)}"></div><div class="field"><label>Фамилия</label><input name="last" required value="${esc(s.last)}"></div><div class="field"><label>Формат</label><select name="format"><option value="individual" ${s.format==='individual'?'selected':''}>Индивидуально</option><option value="pair" ${s.format==='pair'?'selected':''}>Пара</option><option value="group" ${s.format==='group'?'selected':''}>Группа</option></select></div><div class="field"><label>Преподаватель</label><select name="teacher">${optionList(state.teachers,s.teacher)}</select></div><div class="field full"><label>Дни и отдельное время занятий</label><div class="schedule-editor">${DAY_FULL.map((d,i)=>{const slot=slots.find(x=>x.day===i);return `<label class="schedule-slot"><input type="checkbox" name="days" value="${i}" ${slot?'checked':''}><span>${d}</span><input type="time" name="time_${i}" value="${slot?.time||s.time||'16:00'}" aria-label="Время: ${d}"></label>`}).join('')}</div><small>Отметьте нужные дни и задайте для каждого своё время.</small></div><div class="field"><label>Контакт</label><input name="contact" value="${esc(s.contact)}" placeholder="Телефон или Telegram"></div><div class="field"><label>Размер абонемента</label><input name="total" type="number" min="1" max="12" value="${s.total}"></div><div class="field"><label>Осталось уроков</label><input name="remaining" type="number" min="0" max="99" value="${s.remaining}"></div><div class="field full"><label>Заметка</label><textarea name="note" rows="2">${esc(s.note)}</textarea></div><div class="form-actions"><button type="button" class="secondary" data-close>Отмена</button><button class="primary">Сохранить</button></div>`);
  const f=document.querySelector('#modalForm');f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),v=Object.fromEntries(fd),days=fd.getAll('days').map(Number);v.scheduleSlots=days.map(day=>({day,time:fd.get(`time_${day}`)||'16:00'}));v.days=days;v.time=v.scheduleSlots[0]?.time||'16:00';v.total=Number(v.total);v.remaining=Number(v.remaining);id?Object.assign(s,v):state.students.push({...s,...v});await save();closeModal();render();toast('Ученик и расписание сохранены')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal)
}
async function deleteStudent(id){if(!confirm('Удалить ученика из базы?'))return;state.students=state.students.filter(s=>s.id!==id);state.groups.forEach(g=>g.studentIds=g.studentIds.filter(x=>x!==id));state.lessons=state.lessons.filter(l=>l.studentId!==id);await save();render();toast('Ученик удалён')}
function openGroup(id){const g=state.groups.find(x=>x.id===id)||{id:uid(),name:'',type:'group',teacher:state.teachers[0],studentIds:[]};modal(id?'Редактировать группу':'Новая группа или пара','ГРУППЫ',`<div class="field"><label>Название</label><input name="name" required value="${esc(g.name)}"></div><div class="field"><label>Тип</label><select name="type"><option value="group" ${g.type==='group'?'selected':''}>Группа</option><option value="pair" ${g.type==='pair'?'selected':''}>Пара</option></select></div><div class="field full"><label>Преподаватель</label><select name="teacher">${optionList(state.teachers,g.teacher)}</select></div><div class="field full"><label>Участники</label><div class="checkboxes">${state.students.map(s=>`<label class="check-pill"><input type="checkbox" name="studentIds" value="${s.id}" ${g.studentIds.includes(s.id)?'checked':''}><span>${esc(s.first+' '+s.last)}</span></label>`).join('')}</div></div><div class="form-actions"><button type="button" class="secondary" data-close>Отмена</button><button class="primary">Сохранить</button></div>`);const f=document.querySelector('#modalForm');f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),v=Object.fromEntries(fd);v.studentIds=fd.getAll('studentIds');id?Object.assign(g,v):state.groups.push({...g,...v});await save();closeModal();render();toast('Группа сохранена')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal)}
async function deleteGroup(id){if(!confirm('Удалить группу?'))return;state.groups=state.groups.filter(g=>g.id!==id);state.lessons=state.lessons.filter(l=>l.groupId!==id);await save();render();toast('Группа удалена')}

function renderAssistant(){setHeader('AI-помощник','Управляйте всей школой обычными сообщениями');root.innerHTML=`<div class="assistant-layout"><div class="assistant-main card"><div class="assistant-head"><span class="assistant-logo">✦</span><div><strong>Помощник LinguaFlow</strong><small>Полный доступ к ученикам, группам, урокам и абонементам</small></div><span class="badge ${state.pendingAssistantAction?'cancelled':'done'}">${state.pendingAssistantAction?'Ждёт подтверждения':'Готов'}</span></div><div class="chat-messages" id="chatMessages">${state.assistantMessages.map(m=>`<div class="chat-message ${m.role}"><div>${esc(m.text).replace(/\n/g,'<br>')}</div></div>`).join('')}</div><form class="chat-form" id="assistantForm"><textarea name="command" rows="2" required placeholder="Например: добавь ученика Марина Тестова, ПН 16:00, ЧТ 18:30, абонемент 8"></textarea><button class="primary">Отправить ✦</button></form></div><aside class="assistant-tips card"><span class="eyebrow">БЫСТРЫЕ КОМАНДЫ</span><h3>Что можно поручить</h3>${['Добавь ученика Марина Тестова, ПН 16:00, ЧТ 18:30, абонемент 8','Измени ученика Анна Петрова: ВТ 17:00, ПТ 19:00','Создай группу B1 из Анна Петрова и Максим Волков','Составь расписание для всех учеников на этот месяц','Очисти базу учеников','Отмени все предыдущие действия'].map(x=>`<button class="prompt-chip" data-prompt="${esc(x)}">${esc(x)}</button>`).join('')}<p class="assistant-note">Расписание можно создать на этот или следующий месяц. Можно писать сокращения дней: ПН, ВТ, СР, ЧТ, ПТ, СБ, ВС, задавая каждому дню своё время. Массовое удаление требует команды «Подтверждаю». Изменения AI можно отменить.</p></aside></div>`;const box=document.querySelector('#chatMessages');box.scrollTop=box.scrollHeight;document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{document.querySelector('#assistantForm textarea').value=b.dataset.prompt;document.querySelector('#assistantForm textarea').focus()});document.querySelector('#assistantForm').onsubmit=async e=>{e.preventDefault();const input=e.currentTarget.command,value=input.value.trim();if(!value)return;state.assistantMessages.push({role:'user',text:value});input.value='';renderAssistant();const answer=await runAssistantCommand(value);state.assistantMessages.push({role:'assistant',text:answer});state.assistantMessages=state.assistantMessages.slice(-40);await save();renderAssistant()}}

function normalizedWords(text){const aliases={маша:'мария',машу:'мария',саша:'александр',катя:'екатерина',лена:'елена',дима:'дмитрий',макс:'максим',соня:'софия',настя:'анастасия'};return text.toLowerCase().replace(/ё/g,'е').replace(/[.,!?—:;]+/g,' ').split(/\s+/).filter(Boolean).map(w=>aliases[w]||w)}
function findStudentInText(text){const words=normalizedWords(text);let best=null,score=0;for(const s of state.students){const first=s.first.toLowerCase().replace(/ё/g,'е'),last=s.last.toLowerCase().replace(/ё/g,'е');let n=0;if(words.includes(last))n+=4;if(words.includes(first))n+=2;if(words.some(w=>last.startsWith(w)&&w.length>3))n+=2;if(words.some(w=>first.startsWith(w)&&w.length>3))n+=1;if(n>score){score=n;best=s}}return score>=2?best:null}
function parseCommandDate(text){const m=text.match(/\b(\d{1,2})[.\/-](\d{1,2})(?:[.\/-](\d{2,4}))?\b/);if(!m)return null;let y=m[3]?Number(m[3]):new Date().getFullYear();if(y<100)y+=2000;const d=new Date(y,Number(m[2])-1,Number(m[1]));return Number.isNaN(d.getTime())?null:isoDate(d)}
function findStudentLesson(studentId,date){return state.lessons.find(l=>l.date===date&&affectedStudents(l).includes(studentId))}

function titleCase(text){return text.trim().replace(/(^|\s)\S/g,c=>c.toUpperCase())}
function parseCommandDates(text){const matches=[...text.matchAll(/\b(\d{1,2})[.\/-](\d{1,2})(?:[.\/-](\d{2,4}))?\b/g)];return matches.map(m=>{let y=m[3]?Number(m[3]):new Date().getFullYear();if(y<100)y+=2000;return isoDate(new Date(y,Number(m[2])-1,Number(m[1])))})}
function parseWeekdays(text){const names={понедельник:0,понедельникам:0,пн:0,вторник:1,вторникам:1,вт:1,среда:2,средам:2,ср:2,четверг:3,четвергам:3,чт:3,пятница:4,пятницам:4,пт:4,суббота:5,субботам:5,сб:5,воскресенье:6,воскресеньям:6,вс:6},words=normalizedWords(text),days=[];for(const w of words)if(names[w]!==undefined&&!days.includes(names[w]))days.push(names[w]);return days}
function normalizeTime(raw){const [h,m]=raw.replace('.',':').split(':');return `${String(Number(h)).padStart(2,'0')}:${m}`}
function parseExplicitTimes(text){const found=[];for(const m of text.matchAll(/\b([01]?\d|2[0-3]):([0-5]\d)\b/g))found.push(normalizeTime(m[0]));const dayDot=/(?:^|[\s,;])(?:пн|вт|ср|чт|пт|сб|вс|понедельник|вторник|среда|четверг|пятница|суббота|воскресенье)\s+([01]?\d|2[0-3])\.([0-5]\d)(?=$|[\s,;])/gi;for(const m of text.matchAll(dayDot))found.push(normalizeTime(`${m[1]}.${m[2]}`));const atDot=/(?:^|[\s,;])(?:в|время)\s+([01]?\d|2[0-3])\.([0-5]\d)(?=$|[\s,;])/gi;for(const m of text.matchAll(atDot))found.push(normalizeTime(`${m[1]}.${m[2]}`));return found}
function parseScheduleSlots(text){const dayMap={понедельник:0,пн:0,вторник:1,вт:1,среда:2,ср:2,четверг:3,чт:3,пятница:4,пт:4,суббота:5,сб:5,воскресенье:6,вс:6},matches=[...text.matchAll(/(?:^|[\s,;])(понедельник|вторник|среда|четверг|пятница|суббота|воскресенье|пн|вт|ср|чт|пт|сб|вс)(?=$|[\s,;])/gi)],slots=[];for(let i=0;i<matches.length;i++){const from=(matches[i].index||0)+matches[i][0].length,to=i+1<matches.length?matches[i+1].index:text.length,part=text.slice(from,to),tm=part.match(/\b([01]?\d|2[0-3])[.:]([0-5]\d)\b/);if(tm)slots.push({day:dayMap[matches[i][1].toLowerCase()],time:normalizeTime(tm[0])})}if(slots.length===matches.length&&slots.length)return slots;const days=parseWeekdays(text),times=parseExplicitTimes(text);if(!days.length)return[];if(times.length===1)return days.map(day=>({day,time:times[0]}));if(times.length>=days.length)return days.map((day,i)=>({day,time:times[i]}));return[]}
function extractNewStudentName(raw){return raw.split(/\s+(?=(?:пн|вт|ср|чт|пт|сб|вс|понедельник|вторник|среда|четверг|пятница|суббота|воскресенье|преподаватель|учитель|дни|время|формат|абонемент|контакт)(?:\s|,|$)|(?:[01]?\d|2[0-3])[.:][0-5]\d(?:\s|,|$))/i)[0].trim()}
function mentionedStudents(text){const words=normalizedWords(text);return state.students.filter(s=>{const first=s.first.toLowerCase().replace(/ё/g,'е'),last=s.last.toLowerCase().replace(/ё/g,'е');return words.includes(last)||(words.includes(first)&&words.some(w=>last.startsWith(w)&&w.length>3))})}
function findTeacherInText(text){const low=text.toLowerCase().replace(/ё/g,'е');return [...state.teachers].sort((a,b)=>b.length-a.length).find(t=>low.includes(t.toLowerCase().replace(/ё/g,'е')))||null}
function findGroupInText(text){const low=text.toLowerCase().replace(/ё/g,'е');return [...state.groups].sort((a,b)=>b.name.length-a.name.length).find(g=>low.includes(g.name.toLowerCase().replace(/ё/g,'е')))||null}
function queueAssistantAction(type,data,description){state.pendingAssistantAction={type,data,description};return `${description}\nЭто действие может удалить данные. Напишите «Подтверждаю» для выполнения или «Отмена».`}
function performPendingAssistantAction(){const action=state.pendingAssistantAction;if(!action)return 'Нет действия, ожидающего подтверждения.';state.pendingAssistantAction=null;if(action.type==='delete_all_students'){const students=state.students.length,groups=state.groups.length,lessons=state.lessons.length;state.students=[];state.groups=[];state.lessons=[];return `Готово: база учеников очищена. Удалено учеников: ${students}, групп и пар: ${groups}, связанных занятий: ${lessons}. Это действие можно отменить командой «Отмени последнее действие».`}if(action.type==='delete_student'){const s=state.students.find(x=>x.id===action.data.id);if(!s)return 'Ученик уже удалён.';state.students=state.students.filter(x=>x.id!==s.id);state.groups.forEach(g=>g.studentIds=g.studentIds.filter(id=>id!==s.id));state.lessons=state.lessons.filter(l=>l.studentId!==s.id);return `Готово: ${s.first} ${s.last} удалён(а) из базы и из учебных групп.`}if(action.type==='delete_group'){const g=state.groups.find(x=>x.id===action.data.id);if(!g)return 'Группа уже удалена.';const lessons=state.lessons.filter(l=>l.groupId===g.id);lessons.forEach(l=>{l.status='cancelled';reconcileLessonCharges(l)});state.lessons=state.lessons.filter(l=>l.groupId!==g.id);state.groups=state.groups.filter(x=>x.id!==g.id);return `Группа «${g.name}» и связанные с ней занятия удалены.`}if(action.type==='delete_teacher'){const name=action.data.name;state.teachers=state.teachers.filter(t=>t!==name);state.students.forEach(s=>{if(s.teacher===name)s.teacher=''});state.groups.forEach(g=>{if(g.teacher===name)g.teacher=''});state.lessons.filter(l=>l.status==='planned').forEach(l=>{if(l.teacher===name)l.teacher=''});return `Преподаватель ${name} удалён. Активные назначения очищены, история сохранена.`}if(action.type==='delete_lesson'){const l=state.lessons.find(x=>x.id===action.data.id);if(!l)return 'Занятие уже удалено.';l.status='cancelled';reconcileLessonCharges(l);state.lessons=state.lessons.filter(x=>x.id!==l.id);return `Занятие ${fmtDate(new Date(l.date+'T12:00:00'))} удалено, списания возвращены.`}return 'Действие не распознано.'}

async function executeAssistantCommand(text){const low=text.toLowerCase().replace(/ё/g,'е'),student=findStudentInText(text),date=parseCommandDate(text),dates=parseCommandDates(text),teacher=findTeacherInText(text),group=findGroupInText(text);
  if(/^подтвержд|^да,?\s*(удаляй|выполняй)/.test(low))return performPendingAssistantAction();if(low==='отмена'||low==='отмени действие'){state.pendingAssistantAction=null;return 'Ожидающее действие отменено.'}
  if(/(отмени|отменить)\s+все(?:\s+предыдущие)?(?:\s+действия)?/.test(low)){const stack=state.assistantUndoStack||[];if(!stack.length)return 'Нет сохранённых действий AI-помощника, которые можно отменить.';const count=stack.length,snapshot=stack[0];state.assistantUndoStack=[];restoreAssistantSnapshot(snapshot);return `Готово: отменено действий AI-помощника: ${count}. Данные возвращены к состоянию до первого из них.`}
  if(low.includes('отмени последнее')||low.includes('отменить последнее')){const stack=state.assistantUndoStack||[];if(stack.length){const snapshot=stack.pop();restoreAssistantSnapshot(snapshot);return 'Готово: последнее действие AI-помощника отменено.'}const action=state.lastAssistantAction;if(!action?.lessonIds?.length)return 'Нет сохранённого действия, которое можно отменить.';const ids=new Set(action.lessonIds);state.lessons.filter(l=>ids.has(l.id)).forEach(l=>{l.status='cancelled';reconcileLessonCharges(l)});state.lessons=state.lessons.filter(l=>!ids.has(l.id));state.lastAssistantAction=null;return `Готово: удалено ${ids.size} занятий из последнего массового действия.`}
  if(/(?:добавь|добавить|создай|составь|сделай|напиши).*(?:расписан).*до\s+конца\s+(?:этого\s+|текущего\s+)?месяца/.test(low))return createRemainingMonthSchedule();
  if(/(?:создай|составь|сделай|напиши).*(?:расписан).*(?:следующ).*(?:месяц)|(?:следующ).*(?:месяц).*(?:для всех)/.test(low))return createMonthSchedule(1);
  if(/(?:создай|составь|сделай|напиши).*(?:расписан).*(?:этот|текущ(?:ий|ем|его)?|тот)\s+месяц|(?:расписан).*(?:для всех).*(?:этот|текущ(?:ий|ем|его)?|тот)\s+месяц/.test(low))return createMonthSchedule(0);
  if(/(?:очисти|удали|удалить)\s+(?:всю\s+)?(?:базу\s+учеников|всех\s+учеников)/.test(low))return queueAssistantAction('delete_all_students',{},`Очистить базу учеников? Будут удалены ${state.students.length} учеников, ${state.groups.length} групп и пар и ${state.lessons.length} связанных занятий. Преподаватели и настройки останутся.`);

  const addStudent=low.match(/добав(?:ь|ить|ьте)\s+(?:нового\s+)?учени(?:ка|цу)\s+([^,]+)/);if(addStudent&&!/(в группу|в пару)/.test(low)){const raw=extractNewStudentName(addStudent[1]),parts=titleCase(raw).split(/\s+/);if(parts.length<2)return 'Укажите имя и фамилию нового ученика.';if(findStudentInText(raw))return 'Ученик с таким именем уже есть в базе.';let slots=parseScheduleSlots(text);if(!slots.length){const days=parseWeekdays(text),time=parseExplicitTimes(text)[0]||'16:00';slots=(days.length?days:[0,3]).map(day=>({day,time}))}const pack=Math.min(12,Math.max(1,Number(text.match(/абонемент(?:\s+на)?\s+(\d+)/i)?.[1]||8))),format=low.includes('пар')?'pair':low.includes('групп')?'group':'individual',s={id:uid(),first:parts[0],last:parts.slice(1).join(' '),format,teacher:teacher||state.teachers[0]||'',days:slots.map(x=>x.day),time:slots[0].time,scheduleSlots:slots,contact:'',note:'Добавлено AI-помощником',remaining:pack,total:pack,history:[]};state.students.push(s);return `Готово: ${s.first} ${s.last} добавлен(а). ${formatName(format)}, ${studentScheduleText(s)}, абонемент ${pack} уроков.`}
  const renameStudent=text.match(/переименуй\s+учени(?:ка|цу)\s+(.+?)\s+на\s+(.+)/i);if(renameStudent){const target=findStudentInText(renameStudent[1]),parts=titleCase(renameStudent[2]).split(/\s+/);if(!target||parts.length<2)return 'Не удалось определить ученика или новое имя и фамилию.';const old=`${target.first} ${target.last}`;target.first=parts[0];target.last=parts.slice(1).join(' ');return `Ученик ${old} переименован в ${target.first} ${target.last}.`}
  if(/удал(?:и|ить).*(ученика|ученицу)/.test(low)&&!/(из группы|из пары)/.test(low)&&student)return queueAssistantAction('delete_student',{id:student.id},`Удалить ученика ${student.first} ${student.last} из базы?`);
  if(/(измени|редактируй|отредактируй|поменяй).*(учени|данн)|перенеси учени/.test(low)&&student){const changed=[];if(teacher&&teacher!==student.teacher){student.teacher=teacher;changed.push(`преподаватель: ${teacher}`)}const slots=parseScheduleSlots(text);if(slots.length){student.scheduleSlots=slots;student.days=slots.map(x=>x.day);student.time=slots[0].time;changed.push(`расписание: ${studentScheduleText(student)}`)}if(low.includes('индивиду')){student.format='individual';changed.push('индивидуальный формат')}else if(low.includes('пар')){student.format='pair';changed.push('формат: пара')}else if(low.includes('групп')){student.format='group';changed.push('формат: группа')}const contact=text.match(/контакт\s*[:—-]?\s*([^,]+)/i)?.[1];if(contact){student.contact=contact.trim();changed.push('контакт обновлён')}return changed.length?`Карточка ${student.first} ${student.last} обновлена: ${changed.join('; ')}.`:'Я нашёл ученика, но не понял, какое поле изменить. Укажите преподавателя, расписание по дням, формат или контакт.'}

  const renameTeacher=text.match(/переименуй\s+(?:преподавателя|учителя)\s+(.+?)\s+на\s+(.+)/i);if(renameTeacher){const old=findTeacherInText(renameTeacher[1]);if(!old)return 'Исходный преподаватель не найден.';const name=titleCase(renameTeacher[2]);state.teachers[state.teachers.indexOf(old)]=name;state.students.forEach(s=>{if(s.teacher===old)s.teacher=name});state.groups.forEach(g=>{if(g.teacher===old)g.teacher=name});state.lessons.forEach(l=>{if(l.teacher===old)l.teacher=name});return `Преподаватель ${old} переименован в ${name}. Все назначения обновлены.`}
  const addTeacher=low.match(/добав(?:ь|ить)\s+(?:преподавател[ья]|учителя)\s+(.+)/);if(addTeacher){const name=titleCase(addTeacher[1]);if(state.teachers.some(t=>t.toLowerCase()===name.toLowerCase()))return `Преподаватель ${name} уже есть в списке.`;state.teachers.push(name);return `Готово: преподаватель ${name} добавлен.`}
  if(/удал(?:и|ить).*(преподавател|учител)/.test(low)&&teacher)return queueAssistantAction('delete_teacher',{name:teacher},`Удалить преподавателя ${teacher}? Активные назначения будут очищены.`);

  const members=mentionedStudents(text);if(/(создай|собери).*(группу|пару)/.test(low)){if(members.length<2)return 'Назовите минимум двух учеников, которых нужно объединить.';const type=low.includes('пару')?'pair':'group',nameMatch=text.match(/(?:группу|пару)\s+(.+?)\s+(?:из|с учениками|ученики)/i),name=nameMatch?nameMatch[1].trim():members.map(s=>s.first).join(' + ');if(state.groups.some(g=>g.name.toLowerCase()===name.toLowerCase()))return `Группа «${name}» уже существует.`;state.groups.push({id:uid(),name,type,teacher:teacher||members[0].teacher||state.teachers[0]||'',studentIds:members.map(s=>s.id),color:type==='pair'?'#26a875':'#f09b42'});members.forEach(s=>s.format=type);return `Создана ${type==='pair'?'пара':'группа'} «${name}»: ${members.map(s=>`${s.first} ${s.last}`).join(', ')}.`}
  if(/добав(?:ь|ить).*(в группу|в пару)/.test(low)&&student&&group){if(!group.studentIds.includes(student.id))group.studentIds.push(student.id);student.format=group.type;return `${student.first} ${student.last} добавлен(а) в «${group.name}».`}
  if(/(убери|исключи|удали).*(из группы|из пары)/.test(low)&&student&&group){group.studentIds=group.studentIds.filter(id=>id!==student.id);return `${student.first} ${student.last} удалён(а) из «${group.name}».`}
  const renameGroup=text.match(/переименуй\s+(?:группу|пару)\s+(.+?)\s+на\s+(.+)/i);if(renameGroup){const target=findGroupInText(renameGroup[1]);if(!target)return 'Группа для переименования не найдена.';const old=target.name;target.name=renameGroup[2].trim();return `Группа «${old}» переименована в «${target.name}».`}
  if(/удал(?:и|ить).*(группу|пару)/.test(low)&&group)return queueAssistantAction('delete_group',{id:group.id},`Удалить «${group.name}» и все связанные занятия?`);
  if(/(назначь|измени).*(преподавател).*(групп|пар)/.test(low)&&group&&teacher){group.teacher=teacher;return `Преподавателем группы «${group.name}» назначен(а) ${teacher}.`}

  if(/(оформи|добавь|продли).*(абонемент)/.test(low)&&student){const amount=Math.min(12,Math.max(1,Number(text.match(/(\d+)\s*(?:урок|занят)/i)?.[1]||8))),delta=amount-student.remaining;student.total=amount;student.remaining=amount;student.history.push({id:uid(),date:new Date().toISOString(),delta,reason:'Новый абонемент через AI-помощника'});return `Абонемент ${student.first} ${student.last} установлен на ${amount} уроков.`}
  if(/(остаток|оставь).*(\d+)/.test(low)&&student){const amount=Number(low.match(/(?:остаток|оставь)[^\d]*(\d+)/)?.[1]);if(Number.isFinite(amount)){const delta=amount-student.remaining;student.remaining=amount;student.history.push({id:uid(),date:new Date().toISOString(),delta,reason:'Корректировка через AI-помощника'});return `Остаток ${student.first} ${student.last}: ${amount} уроков.`}}
  if(/(сколько|какой).*(остал|абонемент)/.test(low)&&student)return `${student.first} ${student.last}: осталось ${student.remaining} из ${student.total} уроков. Следующий — ${Math.min(student.total-student.remaining+1,student.total)}-й.`;

  if(/(создай|добавь).*(урок|занятие)/.test(low)&&student&&date){const time=parseExplicitTimes(text)[0]||student.time||'16:00',l={id:uid(),date,start:time,end:`${String(Math.min(parseInt(time)+1,23)).padStart(2,'0')}:00`,type:'individual',studentId:student.id,groupId:'',teacher:teacher||student.teacher,status:'planned',note:'Создано AI-помощником',attendance:{},chargedStudentIds:[]};state.lessons.push(l);return `Занятие ${student.first} ${student.last} создано на ${fmtDate(new Date(date+'T12:00:00'))} в ${time}.`}
  if(/перенеси.*(урок|занятие)/.test(low)&&student&&dates.length>=2){const l=findStudentLesson(student.id,dates[0]);if(!l)return 'Исходное занятие не найдено.';l.date=dates[1];const time=parseExplicitTimes(text)[0];if(time){l.start=time;l.end=`${String(Math.min(parseInt(time)+1,23)).padStart(2,'0')}:00`}return `Занятие перенесено на ${fmtDate(new Date(l.date+'T12:00:00'))}${time?` в ${time}`:''}.`}
  if(/(измени|назначь).*(урок|занятие).*(преподавател|учител)/.test(low)&&student&&date&&teacher){const l=findStudentLesson(student.id,date);if(!l)return 'Занятие на указанную дату не найдено.';l.teacher=teacher;return `Для занятия ${fmtDate(new Date(date+'T12:00:00'))} назначен(а) ${teacher}.`}
  if(/удал(?:и|ить).*(урок|занятие)/.test(low)&&student&&date){const l=findStudentLesson(student.id,date);if(!l)return 'Занятие на указанную дату не найдено.';return queueAssistantAction('delete_lesson',{id:l.id},`Удалить занятие ${student.first} ${student.last} ${fmtDate(new Date(date+'T12:00:00'))}?`)}
  if((low.includes('не был')||low.includes('не была')||low.includes('отсутств')||low.includes('пропуск'))&&student&&date){const l=findStudentLesson(student.id,date);if(!l)return `Я нашёл ученика ${student.first} ${student.last}, но на ${fmtDate(new Date(date+'T12:00:00'))} занятия в расписании нет.`;l.attendance=l.attendance||{};l.attendance[student.id]={status:'absent',note:'Отмечено через помощника'};if(affectedStudents(l).length===1)l.status='cancelled';else if(l.status==='planned')l.status='done';reconcileLessonCharges(l);return `Готово: ${student.first} ${student.last} отмечен(а) как отсутствующий(ая). Урок не списан. Осталось: ${student.remaining} из ${student.total}.`}
  if((low.includes('отмени урок')||low.includes('урок отменен')||low.includes('урок отменён'))&&student&&date){const l=findStudentLesson(student.id,date);if(!l)return `На указанную дату занятие не найдено.`;l.status='cancelled';affectedStudents(l).forEach(id=>{l.attendance=l.attendance||{};l.attendance[id]={status:'absent',note:'Урок отменён через помощника'}});reconcileLessonCharges(l);return `Урок отменён. Списание отменено, номер абонемента перенесён.`}
  if((low.includes('проведен')||low.includes('проведён')||low.includes('провести урок'))&&student&&date){const l=findStudentLesson(student.id,date);if(!l)return 'Занятие на указанную дату не найдено.';l.status='done';affectedStudents(l).forEach(id=>{l.attendance=l.attendance||{};if(!l.attendance[id])l.attendance[id]={status:'present',note:''}});reconcileLessonCharges(l);return `Урок проведён. У присутствующих учеников списано по одному занятию.`}
  if(!student&&date)return 'Я вижу дату, но не нашёл ученика. Напишите имя и фамилию как в базе.';
  return 'Я могу изменять учеников, преподавателей, группы, расписание, посещаемость и абонементы. Напишите конкретное действие, имя и необходимые данные. Для удаления потребуется подтверждение.'}

function createMonthSchedule(monthOffset=1){const now=new Date(),start=new Date(now.getFullYear(),now.getMonth()+monthOffset,1),end=new Date(now.getFullYear(),now.getMonth()+monthOffset+1,1),created=[],grouped=new Set(state.groups.flatMap(g=>g.studentIds)),skipped=[];const datesFor=slots=>{const result=[];for(let d=new Date(start);d<end;d=addDays(d,1)){const day=(d.getDay()+6)%7,slot=slots.find(x=>x.day===day);if(slot)result.push({date:isoDate(d),time:slot.time})}return result};const addTarget=(target,slots)=>{const safeSlots=slots.length?slots:[{day:0,time:'16:00'},{day:3,time:'16:00'}],candidates=datesFor(safeSlots),existing=state.lessons.filter(l=>l.date>=isoDate(start)&&l.date<isoDate(end)&&(target.groupId?l.groupId===target.groupId:l.studentId===target.studentId)).length;let needed=Math.max(0,8-existing);for(const candidate of candidates){if(!needed)break;const {date,time}=candidate;if(state.lessons.some(l=>l.date===date&&l.start===time&&(target.groupId?l.groupId===target.groupId:l.studentId===target.studentId)))continue;const lesson={id:uid(),date,start:time,end:`${String(Math.min(parseInt(time)+1,23)).padStart(2,'0')}:00`,type:target.type,studentId:target.studentId||'',groupId:target.groupId||'',teacher:target.teacher,status:'planned',note:'Создано AI-помощником',attendance:{},chargedStudentIds:[]};state.lessons.push(lesson);created.push(lesson.id);needed--}if(needed)skipped.push(target.name)};for(const g of state.groups){const members=g.studentIds.map(id=>state.students.find(s=>s.id===id)).filter(Boolean),base=members[0];if(!base){skipped.push(g.name);continue}addTarget({groupId:g.id,type:g.type,teacher:g.teacher,name:g.name},base.scheduleSlots||[])}for(const s of state.students.filter(s=>!grouped.has(s.id)))addTarget({studentId:s.id,type:'individual',teacher:s.teacher,name:`${s.first} ${s.last}`},s.scheduleSlots||[]);if(created.length)state.lastAssistantAction={type:'create_lessons',lessonIds:created};const month=new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(start);return `Готово: на ${month} создано ${created.length} занятий с отдельным временем для каждого дня. Для каждого ученика или группы учтено до 8 записей.${skipped.length?` Не хватило подходящих дат: ${skipped.join(', ')}.`:''}${created.length?'\nЕсли нужно, напишите «Отмени последнее действие».':''}`}
function createNextMonthSchedule(){return createMonthSchedule(1)}
function createRemainingMonthSchedule(){
  const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),now.getDate()),end=new Date(now.getFullYear(),now.getMonth()+1,1),created=[],grouped=new Set(state.groups.flatMap(g=>g.studentIds)),skipped=[];
  const datesFor=slots=>{const result=[];for(let d=new Date(start);d<end;d=addDays(d,1)){const day=(d.getDay()+6)%7,slot=slots.find(x=>x.day===day);if(slot)result.push({date:isoDate(d),time:slot.time})}return result};
  const addTarget=(target,slots)=>{const safeSlots=slots.length?slots:[{day:0,time:'16:00'},{day:3,time:'16:00'}],candidates=datesFor(safeSlots),existing=state.lessons.filter(l=>l.date>=isoDate(start)&&l.date<isoDate(end)&&(target.groupId?l.groupId===target.groupId:l.studentId===target.studentId)).length;let needed=Math.max(0,8-existing);for(const candidate of candidates){if(!needed)break;const {date,time}=candidate;if(state.lessons.some(l=>l.date===date&&l.start===time&&(target.groupId?l.groupId===target.groupId:l.studentId===target.studentId)))continue;const lesson={id:uid(),date,start:time,end:`${String(Math.min(parseInt(time)+1,23)).padStart(2,'0')}:00`,type:target.type,studentId:target.studentId||'',groupId:target.groupId||'',teacher:target.teacher,status:'planned',note:'Создано AI-помощником',attendance:{},chargedStudentIds:[]};state.lessons.push(lesson);created.push(lesson.id);needed--}if(needed)skipped.push(target.name)};
  for(const g of state.groups){const members=g.studentIds.map(id=>state.students.find(s=>s.id===id)).filter(Boolean),base=members[0];if(!base){skipped.push(g.name);continue}addTarget({groupId:g.id,type:g.type,teacher:g.teacher,name:g.name},base.scheduleSlots||[])}
  for(const s of state.students.filter(s=>!grouped.has(s.id)))addTarget({studentId:s.id,type:'individual',teacher:s.teacher,name:`${s.first} ${s.last}`},s.scheduleSlots||[]);
  if(created.length)state.lastAssistantAction={type:'create_lessons',lessonIds:created};
  const lastDay=fmtDate(addDays(end,-1));
  return `Готово: до ${lastDay} создано ${created.length} занятий, начиная с сегодняшнего дня. Использовано отдельное время для каждого дня.${skipped.length?` Не хватило подходящих дат: ${skipped.join(', ')}.`:''}${created.length?'\nЕсли нужно, напишите «Отмени последнее действие».':''}`;
}
function openSubscription(id){const s=state.students.find(x=>x.id===id);modal('Изменить абонемент','АБОНЕМЕНТ',`<div class="field full"><label>Ученик</label><input disabled value="${esc(s.first+' '+s.last)}"></div><div class="field"><label>Размер пакета (1–12)</label><input name="total" type="number" min="1" max="12" value="${s.total}"></div><div class="field"><label>Новый остаток</label><input name="remaining" type="number" min="0" max="99" value="${s.remaining}"></div><div class="field full"><label>Причина изменения</label><input name="reason" required placeholder="Например: оплата нового абонемента"></div><div class="field full"><label>История</label><div class="low-list">${s.history.slice().reverse().slice(0,8).map(h=>`<div class="low-row"><strong>${h.delta>0?'+':''}${h.delta}</strong><div><span>${esc(h.reason)}</span><small>${new Date(h.date).toLocaleString('ru-RU')}</small></div></div>`).join('')||'<small>Изменений пока нет</small>'}</div></div><div class="form-actions"><button type="button" class="secondary" data-close>Отмена</button><button class="primary">Сохранить</button></div>`);const f=document.querySelector('#modalForm');f.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(f)),next=Number(v.remaining),delta=next-s.remaining;s.total=Number(v.total);s.remaining=next;s.history.push({id:uid(),date:new Date().toISOString(),delta,reason:v.reason});await save();closeModal();render();toast('Абонемент обновлён')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal)}

function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportJSON(){download(`linguaflow-backup-${isoDate(new Date())}.json`,JSON.stringify(state,null,2),'application/json');toast('Резервная копия скачана')}
function exportICS(){const pad=n=>String(n).padStart(2,'0'),stamp=(date,time)=>{const d=new Date(`${date}T${time}:00`);return `${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}T${pad(d.getHours())}${pad(d.getMinutes())}00`};const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//LinguaFlow//School Schedule//RU','CALSCALE:GREGORIAN',...state.lessons.flatMap(l=>['BEGIN:VEVENT',`UID:${l.id}@linguaflow`, `DTSTART:${stamp(l.date,l.start)}`,`DTEND:${stamp(l.date,l.end)}`,`SUMMARY:${lessonName(l)} — ${formatName(l.type)}`,`DESCRIPTION:Преподаватель: ${l.teacher}${l.note?'\\n'+l.note:''}`,'END:VEVENT']),'END:VCALENDAR'];download('linguaflow-schedule.ics',lines.join('\r\n'),'text/calendar;charset=utf-8');toast('ICS-файл готов')}
function bindCommon(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{currentView=b.dataset.go;render()});document.querySelectorAll('[data-edit-lesson]').forEach(b=>b.onclick=()=>openLesson(b.dataset.editLesson));document.querySelectorAll('[data-edit-sub]').forEach(b=>b.onclick=()=>openSubscription(b.dataset.editSub))}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{currentView=b.dataset.view;document.querySelector('#sidebar').classList.remove('open');render()});document.querySelector('#quickAdd').onclick=()=>openLesson();document.querySelector('#menuBtn').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');document.querySelector('#exportBtn').onclick=exportJSON;document.querySelector('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){filters.query=e.target.value;currentView='students';render()}};document.querySelector('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')closeModal()};document.querySelector('#resetDemo').onclick=async()=>{if(confirm('Восстановить демонстрационные данные? Текущие данные будут заменены.')){state=demo();normalizeState();await save();render();toast('Демо-данные восстановлены')}};
load();
